class InputList:
    def __init__(self, input_list):
        self.inputList = input_list

allCategories = InputList([
        '',
        'Atlas',
        'Avalon Consumer Website',
        'Bluecow',
        'CallMiner',
        'Cosmos Consumer Website',
        'Dynamics',
        'Enterprise',
        'EU Ops',
        'Event Notification',
        'Globus Consumer Website',
        'Hardware',
        'Hubs',
        'Inquiry',
        'M365',
        'MyAvalon',
        'MyCosmos',
        'MyGlobus',
        'Network',
        'Payments',
        'Security',
        'Surveys',
        'TD Portal',
        'Telecom',
        'Travel Advisor Portal (TAP) Asia/AU/CA/NZ/US/ZA',
        'Travel Advisor Portal (TAP) IN/UK',
        'Websites'
    ])

allSubCategories = InputList([
        '',
        'Access',
        'Account Creation Request',
        'Accounting',
        'Air',
        'AirHub',
        'Appliance',
        'API Support',
        'Authenticator',
        'AvalonGo App (Web Page Only)',
        'Booking',
        'Broken Functionality',
        'Call Centre',
        'CCS: Sales Control',
        'Circuit',
        'Citrix',
        'Communications',
        'Conference Phone',
        'Connectivity',
        'Content',
        'Content Hub',
        'Content/Products',
        'Contract/Inventory',
        'CosmosGo App (Web Page Only)',
        'Customer Survey',
        'Data Loss/Breach',
        'Data Maintenance',
        'Desktop',
        'DHCP',
        'Docking Location',
        'Docking Station',
        'Documents',
        'Dynamics Customer Insight',
        'Dynamics Customer Service',
        'Dynamics Marketing',
        'Dynamics Navision',
        'Dynamics Sales',
        'Emergency Contacts',
        'Error',
        'Event',
        'Excel',
        'Excursion Portal',
        'Firewall',
        'Forms',
        'FTP',
        'GFOB University',
        'GlobusGo App (Web Page Only)',
        'Groups',
        'Guest Acknowledgement',
        'Headset',
        'Internet',
        'Keyboard/Mouse',
        'LAN',
        'Laptop',
        'Latency',
        'Login',
        'Login/Logout',
        'Make a Payment',
        'Malfunction/failure',
        'Malicious Software (Virus / Malware / Ransomware)',
        'Media Repository',
        'Missing/lost/stolen',
        'Monitor',
        'My Accommodations',
        'My Documentation',
        'My Excursions',
        'My Profile',
        'My Vouchers',
        'My Wallet',
        'MySites',
        'Network Drivers',
        'Network Speed Slow',
        'Non-Credit Card',
        'Number Routing',
        'Operating',
        'Optionals',
        'Optional Excursions',
        'Ops Portal',
        'ORCA',
        'Orca (Eport Central)',
        'ORS',
        'Other',
        'Outage',
        'Outlook App',
        'Outlook Email',
        'Passenger Registration',
        'Password Locked - Reset',
        'Password Reset Issue',
        'Payments',
        'Payroll',
        'Phishing',
        'Phone Queue',
        'Physical Security',
        'Planning',
        'Policy Violation',
        'Power Automate',
        'PowerBI',
        'PowerPoint',
        'Printer Copier',
        'Print Excursion',
        'Product/Inventory Data Loading',
        'Promos',
        'Promotion',
        'Reservation Communications',
        'Reservations (Booking)',
        'ResHub',
        'RingCentral MAX',
        'SalesHub',
        'Security Event/Message',
        'SharePoint',
        'Siebel',
        'SMS: Services Management System',
        'Social Engineering',
        'Spam',
        'Suspicious Activity (email / spam / phish)',
        'TAPs',
        'TD Portal',
        'Teams',
        'The Source',
        'Theft (Assets/IP)',
        'TOPS',
        'Tour Report',
        'Transfer Engine',
        'TRAMS',
        'UK Reporting',
        'User ID / PW Issue / Compromise',
        'View Vacation Overview',
        'Virus/Malware Alert',
        'Voicemail',
        'Vouchers',
        'VPN',
        'Wired',
        'Wireless',
        'Word',
        'Work Requests',
        'Workflow'
    ])

